version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      SELENIUM_DRIVER_URL: "http://selenium_chrome:4444/wd/hub"
      REDIS_URL: redis://redis:6379
      region: ap-northeast-1
      access_key_id: AWS_ACCESS_KEY_ID
      secret_access_key: AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/renraku_app
      - public-data:/renraku_app/public
      - tmp-data:/renraku_app/tmp
      - log-data:/renraku_app/log
    depends_on:
      - db
      - chrome
      - redis
    networks:
      - default
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" &&  bundle exec puma -C config/puma.rb

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/renraku_app/public
      - tmp-data:/renraku_app/tmp
    ports:
      - 80:80
    depends_on:
      - app

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/renraku_app
      - ./data/redis:/data
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  mysql_data:
  public-data:
  tmp-data:
  log-data:
